#include <Windows.h>
#include <vector>
#include "Windows.h"
#include <TlHelp32.h>
#include <iostream>
#include "offsets.hpp"
#include <cstdint>
#include <cstddef>
#include "Xor.h"
#include "MemoriaTest.h"
#include "LocalPlayer.h"
#include "Entidad.h"
#include <stdlib.h>
#include "NoFlash.h"
#include "GlowESP.h"
#include "Bunnyhop.h"
#include "Radar.h"
#include <corecrt_math_defines.h>
#include <math.h>
#include <d3d9.h>
#include <d3dx9.h>
#include "RCS.h"
#include "Triggerbot.h"
#include "W2S.h"
#include "Math.h"
#include "Aimbot.h"
#include "Chams.h"
#include "Fovchanger.h"